### ISSUE TITLE
Don't work: 'php' could not be spawned.

### ISSUE THREAD

**Issue by marek1545** [Azakur4/autocomplete-php#11]
I had funny problem. I install your package  And when i go to php files and start writing a have problem: 

'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Can't you tell step by step install process. Maybe I should add or change something in files autocomplete?

**Comment by Azakur4** [comment]
Like say the realm in the package u need have php in ur environment path to run it. What OS u have?

**Comment by marek1545** [comment]
Ok I understand that i must declarate path but i don't where in settings? in  file autocomplet-plus but in which?. I start use atom from 24 hours. Sorry for problem.

**Comment by Azakur4** [comment]
u need to config in ur operation system the environment path if u have windows u can do this:

Editing Environmental Variables
First, we shall set the environmental variables we need to ensure the PHP can be used by Apache.

In all versions of Windows:

Right click the My Computer icon and open the Properties dialogue.

Go to "Advanced" or "Advances System Variables" and then to "Environment Variables" and in the "System variables" section select "Path" and click the Edit button.

At the end of the path statement, add the text ";C:\put-the-path-of-ur-php-folder\bin" Note the first character is a semi-colon, this is a separator, it separates different parts of the path statement, do not forget to put it in, and do not put it at the end of the line. There are no spaces in the path statement. Save the file by clicking on OK. Close and exit the My Computer Properties dialogue.

**Comment by jeroldhaas** [comment]
Since many other linters support a configuration where one may enter the full path of `php.exe`, it might be a good idea to have the `PATH` environment as an optional choice for when nothing is entered into the "path to `php` executable."

**Comment by ArakTaiRoth** [comment]
My development environment is on Windows and I've installed this package. As soon as I try typing anything inside a PHP file I get the titled error, more specifically, "'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.". This is followed by an error in the console, "Uncaught Error: spawn php ENOENT".

I have verified this is the package causing the problem as the problem disappears as soon as I disable only this package. In addition I have verified that the directory for PHP is in my path, and has been loaded by Atom, by checking the process.env.PATH variable while loaded. I also have verified that it is functioning on my system with the command "php -v", which I can run from any directory.

Sorry to dredge up an old topic, but it's the exact same situation, so I felt it was appropriate here.

**Comment by Azakur4** [comment]
Hi Arak what version of window u are using?

**Comment by ArakTaiRoth** [comment]
Windows 8.1

**Comment by Azakur4** [comment]
umm that is rare, im testing in a windows 8.1 and works fine. this happen to u in every php file or maybe in one in special.

**Comment by ArakTaiRoth** [comment]
The problem appears to have gone away with the latest update (just updated 30 minutes ago). So I guess we can say this is solved.

**Comment by manan88** [comment]
Hello ArakTaiRoth

I am using Windows 8.1 and getting this error after installing automplete-php package.

'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Can you please guide me how to fix that.

Thanks.

**Comment by jeroldhaas** [comment]
@manan88 `php.exe` has to be added to the `PATH` system environment variable.

# Again I strongly suggest that instead of relying on PATH, a simple text box be added to configuration so the end-user can point to whichever php.exe they choose

**Comment by manan88** [comment]
@jeroldhaas Sorry but I am not technical but can you guide me step by step to resolve this error. I will thankful if you support me :)

**Comment by jeroldhaas** [comment]
You'll need PHP installed on your machine. Find the location of the file `php.exe` on your computer (on my machine it's at `c:\xampp\php\`). This is the folder that you'll need to add to your system PATH.

To set PATH environment variable, go to Control Panel and type `environ` into the search at top, like this:
![image](https://cloud.githubusercontent.com/assets/835976/8755108/7428bd42-2c96-11e5-9c16-2bbadbc933ae.png)

Click on "Edit the system environment variables," and then click on the "Environment Variables..." button.
![image](https://cloud.githubusercontent.com/assets/835976/8755143/b14d618c-2c96-11e5-912f-d98b15ad5211.png)

On the lower section of the new window that opens, find `Path` and edit that. Each entry to this variable is separated by a `;` so be sure to add that first to the end, then the path to where you have `php.exe` installed.

After you make these changes, restart Atom. You may need to log out of Windows and log back in, possibly even restart the computer, for the changes to `PATH` to take effect.

**Comment by manan88** [comment]
@jeroldhaas Thanks for the great support. Now I am getting php automplete :) :+1:

**Comment by wasikuss** [comment]
Maybe better will be adding option in settings to manually specify path if it is not in `PATH`?

Like in `linter-php`:
![capture](https://cloud.githubusercontent.com/assets/9192409/9231852/bcabccd2-412a-11e5-8649-abb5c379b02b.PNG)

I can do PR.

**Comment by jeroldhaas** [comment]
@wasikuss that would be optimal, yes, with a default to `PATH` if the text box is empty. :smile:

**Comment by hao203** [comment]
My system is win10, I add them to the PATH system environment variable, but it still not work

**Comment by jeroldhaas** [comment]
@hao203 It's better now to configure the package by entering the path to php executable in package settings, since that option has been added.

**Comment by DAV9854** [comment]
Hi @Azakur4 , I too am having the same issue but I am running xubuntu 14.04 LTS. How would I configure it so this error stops occurring?

**Comment by jeroldhaas** [comment]
@DAV9854 make sure your `php` executable has execute bit set for the user / group trying to run it. You may have to add that user to the same group the `php` executable is ownership is set.

**Comment by DAV9854** [comment]
Thanks @jeroldhaas, I am now able to run this error free!

**Comment by SylannBin** [comment]
Hi everyone, I'm having big troubles using linter-php.
both php folder and php.exe are set in my path.
When I added it to the settings relevant section of the linter-php package, it has been working for ... say 2 seconds.
Immediatly after that, i had the same errors back :

**Comment by muwu0505** [comment]
@jeroldhaas Thanks for the great support,it's useful!!!  :)

**Comment by miyanialkesh7** [comment]
I am using XAMPP 7.0.9 with ubuntu 16.04 system. Is there any help possible to resolve the same issue?

**Comment by 8Ozymandias** [comment]
@jeroldhaas I appreciate the thoroughness of your response. I have found that many answers and explanations and or READMEs are very lacking at least from the perspective of beginners or newbs. Please continue being a great help and giving clear explanations for e.g. with pictures like you did responding to @manan88

**Comment by rahuls360** [comment]
1) Find the location of your php.exe file
2) Search for php.exe in your main drive in the file explorer (C Drive for me)
3) My location was C:\xampp\php\php.exe
4) Add it as system variable (as mentioned by @jeroldhaas )
5) Give the path as the parent folder of php.exe (C:\xampp\php)
6) Press Ok and save changes

To test if its working
1) Open cmd
2) type 'php -v' from any file path other than (C:\xampp\php)
3) If you get a version number as output, its working. 
4) Restart Atom and verify

**Comment by artembusygin** [comment]
Спасибо. Очень помогли с решением данной проблемы.

**Comment by Trevorton27** [comment]
Thank you for posting this. This was a really frustrating thing to deal with. I lost about an hour trying to figure it out on my own. :-)

Awesome solution.

**Comment by Ri-Drach** [comment]
Thank you @jeroldhaas , I followed all your steps on my pc  and it is works perfectly.

**Comment by jetr6445** [comment]
Thanks!!! @rahuls360

**Comment by saidbakr** [comment]
> @DAV9854 make sure your `php` executable has execute bit set for the user / group trying to run it. You may have to add that user to the same group the `php` executable is ownership is set.

I have the same issue on Ubuntu 18.04. However, I could not able to do what you have said about execution permissions. In other words, I don't know how to do it?
