### ISSUE TITLE
Hello ~~~~~ Who are here !!

### ISSUE THREAD

**Issue by gclove** [Azakur4/autocomplete-php#19]
Why I can't use it in mac and php 5.6.10

**Comment by Azakur4** [comment]
Hi @XMap sorry i never tested the package with php 5.6.10 but i will try to help u. Atom give u some error message or something like that if u execute php -v in the terminal u get the version of ur php?

**Comment by XMap** [comment]
Wow ~~ Thank you .
```
$ php -v
PHP 5.6.10 (cli) (built: Jun 12 2015 10:07:24)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by XMap** [comment]
And about Atom  it show me that 
![Image of Atom](http://i.minus.com/iDdd4Zp3ByLEd.png)

**Comment by XMap** [comment]
With the  /etc/paths  file .

```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
~/.composer/vendor/bin
/usr/local/Cellar/php56/5.6.10/bin

**Comment by Azakur4** [comment]
Sorry man i doesn't test this package with php 5.6 if u can execute the php -v in ur terminal the php is in the environment path of ur OS. actually i use in my mac the native php and work like a charm.

if this package doesn't help u try to use the package of peekmo search in atom packages.

**Comment by luishdez** [comment]
I use this with mac and 5.6 with no problem 

btw thats a weird title for an issue …
