### ISSUE TITLE
Function completion?

### ISSUE THREAD

**Issue by amp343** [Azakur4/autocomplete-php#3]
Saw this repo, looks pretty cool. Are you interested in including function completion? If so I would be willing to contribute some to that part.

I added a few `array...` functions to a fork:
(https://github.com/amp343/autocomplete-php)

So that they should complete like:
- you type: `array_fil`
- autocomplete: `array_filter($array)`

**Comment by Azakur4** [comment]
yes im interested in including the function completion send me a pull request an i will go review the code to see is this work with the new thinks im doing.

U can see my other branch phpProcess in this repo. In that branch the autocompletion for user functions work including snippets for the functions but have a problem u need have php in ur path environment to work. Is a tentative that im working on.

**Comment by Azakur4** [comment]
Nice work man i merge ur pull request thanks. i will close this.

**Comment by Azakur4** [comment]
Hey @amp343 i see that u put the parameters in json like a new array and after that u join the parameters in text property inside providers.

U can modify this and make it better with the snippet property. u can see some examples in the completions.json for keywords.

if u don't have time to do this maybe i can do it, thanks in advance.

**Comment by amp343** [comment]
cool, ill take a look a bit later on.

**Comment by amp343** [comment]
Check out the new pull request: parameters as snippets.

**Comment by Azakur4** [comment]
Nice work man i will close this issue ur pull request was merged thanks for all the effort to make this better.
