### ISSUE TITLE
'php' could not be spawned error

### ISSUE THREAD

**Issue by signmein** [Azakur4/autocomplete-php#35]
Hi,

After I installed this package, I noticed the error attached every time I'm typing a character in my php file. Please see attached screenshot
![screenshot_8](https://cloud.githubusercontent.com/assets/6081274/16543416/b4b04838-4105-11e6-812c-d3452d9fb3ac.jpg).

Regards,
Felix

**Comment by Azakur4** [comment]
try to configure the extension, have an option to put the path of ur php
