### ISSUE TITLE
PHP could not be spawned

### ISSUE THREAD

**Issue by ChristianGrech** [Azakur4/autocomplete-php#6]
After updating to v 0.3.0 I am getting the below error. I am using the latest atom 0.198.0

![image](https://cloud.githubusercontent.com/assets/4950218/7551584/107b4500-f68e-11e4-9f7d-625344bf0955.png)
Devtools Console:
![image](https://cloud.githubusercontent.com/assets/4950218/7551592/45f479cc-f68e-11e4-9785-9a7aedeb0442.png)

**Comment by Azakur4** [comment]
u are in what platform?

**Comment by ChristianGrech** [comment]
This was working with the previous version... 
cmd output:
'php' is not recognized as an internal or external command, operable program or batch file.

**Comment by Azakur4** [comment]
ohh in the new version u need to have php in ur enviroment path to work properly cuz now the extesion support user functions and other new features. do u know how add the php to ur enviroment path?

**Comment by ChristianGrech** [comment]
I see, would be nice to highlight it in the requirements page :) Thanks for your swift response

**Comment by Azakur4** [comment]
is it man :) see the readme

**Comment by ChristianGrech** [comment]
Yes I checked it now. But putting it in bold or something just to attract attention. Or handle the error better by giving a detailed error prompt to the user if there is not php in the environment path. Just a suggestion to avoid more issue

**Comment by Azakur4** [comment]
yeah i know thanks for point that i will do it in the next release. can i close this issue?

**Comment by ChristianGrech** [comment]
Yes it worked now :) Awesome feature was really looking forward to have custom functions in the autocomplete. Just one suggestion; could you recognize the functions of an object, it is really handy.

**Comment by Azakur4** [comment]
Is the next step will be a little hard but will try. Actually im trying to fix and issue with clousure functions. after that i will see what i can do with the functions of an object.

Is good to know is working all for u i will close this ok.
